export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const GET_COUNTRY_DETAIL = 'GET_COUNTRY_DETAIL';
export const GET_COUNTRY_NAME = 'GET_COUNTRY_NAME';


export const ORDER = 'ORDER';
export const ORDER_BYPOPULATION = 'ORDER_BYPOPULATION';
export const FILTER_BYCONTINENT = 'ORDER_BYCONTINENT';
export const FILTER_BYACTIVITIES = 'FILTER_BYACTIVITIES';
//export const FILTER_FROM_DOGS = 'FILTER_FROM_DOGS';

export const GET_ALL_ACTIVITIES = 'GET_ALL_ACTIVITIES';
export const ADD_ACTIVITY = 'ADD_ACTIVITY';


export const CLEAN_DETAIL = 'CLEAN_DETAIL'
export const CLEAN_FILTER = 'CLEAN_FILTER'